#web server
server:
  tomcat:
    max-threads: 1000


be:
  phone_message_per_day: 10


mybatis:
    mapper-locations: "classpath*:**/com.masou.coupon.data.mappers/*.xml"


logging:
  config: "classpath:log4j2-spring.yml"
  sentry:
    enabled: false

spring:
    application:
        name: webyb
    profiles:
        active: test
    #redis server
    redis:
      host: 119.23.242.204
      port: 6379
      password: Yyc51Linghui
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    #  context-path: /finance




#测试环境
---

spring:
    profiles: test


    datasource:
        name: redpackage
        url: jdbc:mysql://119.23.242.204:3306/coupon?useUnicode=true&characterEncoding=UTF-8
        username: linghui
        password: Yyc51Linghui
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


#生产环境
---

spring:
    profiles: prod


    datasource:
        name:
        url:
        username:
        password:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20